### ISSUE TITLE
Read the Docs Builds Fail

### ISSUE THREAD

**Issue by nhandler** [Yelp/yelp_clog#4]
Currently the docs fail to build on Read the Docs with the follow error on this step:

`python /home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

> Running Sphinx v1.3.1
> making output directory...
> 
> Traceback (most recent call last):
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
>     opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 126, in __init__
>     confoverrides or {}, self.tags)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/sphinx/config.py", line 277, in __init__
>     execfile_(filename, config)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/sphinx/util/pycompat.py", line 128, in execfile_
>     exec_(code, _globals)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/six.py", line 699, in exec_
>     exec("""exec _code_ in _globs_, _locs_""")
>   File "<string>", line 1, in <module>
>   File "conf.py", line 43, in <module>
>     from clog import __version__ as version
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/checkouts/latest/clog/__init__.py", line 34, in <module>
>     from clog.loggers import ScribeLogger, ScribeIsNotForkSafeError
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/checkouts/latest/clog/loggers.py", line 62, in <module>
>     scribe_thrift = _load_thrift()
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/checkouts/latest/clog/loggers.py", line 59, in _load_thrift
>     fn, module_name='scribe_thrift', include_dirs=[include_dir])
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/thriftpy-0.3.2-py2.7-linux-x86_64.egg/thriftpy/parser/__init__.py", line 30, in load
>     include_dir=include_dir)
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/thriftpy-0.3.2-py2.7-linux-x86_64.egg/thriftpy/parser/parser.py", line 484, in parse
>     with open(path) as fh:
> IOError: [Errno 2] No such file or directory: 'scribe.thrift'
> 
> Exception occurred:
>   File "/home/docs/checkouts/readthedocs.org/user_builds/yelp-clog/envs/latest/local/lib/python2.7/site-packages/thriftpy-0.3.2-py2.7-linux-x86_64.egg/thriftpy/parser/parser.py", line 484, in parse
>     with open(path) as fh:
> IOError: [Errno 2] No such file or directory: 'scribe.thrift'
> The full traceback has been saved in /tmp/sphinx-err-LNhokb.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!

**Comment by ecanzonieri** [comment]
It looks like we need to build the thrift interface before the docs

**Comment by ecanzonieri** [comment]
it seems that yelp_clog is not compatible with the latest version of thriftpy, which is 0.3.2

**Comment by nhandler** [comment]
Some combination of pinning the thriftpy version and adding a MANIFEST.in file to ensure that we are including the .thrift files fixed this issue. Docs are now available at http://yelp-clog.readthedocs.org/
