### ISSUE TITLE
Uwsgi Plugin serialization format

### ISSUE THREAD

**Issue by tiras-j** [Yelp/yelp_clog#42]
RE: [My recent PR](https://github.com/Yelp/yelp_clog/pull/41) we know that marshal is dangerous but fast. However doing some rudimentary testing I think using struct + simple byte concat is faster on pre-Python3.5 (apparently someone decided to overhaul the `marshal` serialization I suppose). Here's a rudimentary [test script](https://gist.github.com/tiras-j/5c0357b5a68ad9504d2045febbebd512) I used to run some very basic timings. Using this approach means we have to deal with unicode vs. bytes ourselves, but since clog converts lines into UTF-8 anyways I don't think that will be much of an issue. How about stream names? It doesn't look like the ScribeLogger converts that to UTF-8, so we might need to reconstitute the unicode format by storing the encoding somehow.

Anyways, struct + raw bytes would be safer than `marshal` and would work in this case since we can make some strong assumptions about the arguments. I'll look into changing it but I think we should get the current PR in first just to fix the `marshal.loads` problem.

**Comment by asottile** [comment]
iirc the thrift stuff allows either UTF-8 bytes or text, so encoding the stream name should be safe
